apiVersion: v1
kind: Service
metadata:
  name: {{ include "nvidia-gpu-exporter.fullname" . }}
  labels:
    {{- include "nvidia-gpu-exporter.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
      {{- if and (.Values.service.nodePort) (or (eq .Values.service.type "NodePort") (eq .Values.service.type "LoadBalancer")) }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
  selector:
    {{- include "nvidia-gpu-exporter.selectorLabels" . | nindent 4 }}
---

apiVersion: v1
kind: Service
metadata:
  name: {{ include "nvidia-gpu-exporter.fullname" . }}-headless
  annotations:
    prometheus.io/path: /metrics
    prometheus.io/port: "9835"
    prometheus.io/scheme: http
    prometheus.io/scrape: "true"
  labels:
    {{- include "nvidia-gpu-exporter.labels" . | nindent 4 }}
    app.kubernetes.io/managed-by: kubeblocks
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: http
    protocol: TCP
    name: http
      {{- if and (.Values.service.nodePort) (or (eq .Values.service.type "NodePort") (eq .Values.service.type "LoadBalancer")) }}
    nodePort: {{ .Values.service.nodePort }}
      {{- end }}
  selector:
    {{- include "nvidia-gpu-exporter.selectorLabels" . | nindent 4 }}
